if(NOT DEFINED GIT_EXECUTABLE)
  message(FATAL_ERROR "GIT_EXECUTABLE is required")
endif()
if(NOT DEFINED SOURCE_DIR)
  message(FATAL_ERROR "SOURCE_DIR is required")
endif()
if(NOT DEFINED PATCH_FILE)
  message(FATAL_ERROR "PATCH_FILE is required")
endif()

execute_process(
  COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" apply --reverse --check "${PATCH_FILE}"
  RESULT_VARIABLE PATCH_ALREADY_APPLIED
  OUTPUT_QUIET
  ERROR_QUIET
)

if(PATCH_ALREADY_APPLIED EQUAL 0)
  message(STATUS "Patch already applied: ${PATCH_FILE}")
  return()
endif()

execute_process(
  COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" apply --check "${PATCH_FILE}"
  RESULT_VARIABLE PATCH_CAN_APPLY
  OUTPUT_VARIABLE PATCH_CHECK_OUTPUT
  ERROR_VARIABLE PATCH_CHECK_ERROR
)

if(NOT PATCH_CAN_APPLY EQUAL 0)
  message(FATAL_ERROR "Patch cannot be applied: ${PATCH_FILE}\n${PATCH_CHECK_OUTPUT}\n${PATCH_CHECK_ERROR}")
endif()

execute_process(
  COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" apply --whitespace=nowarn "${PATCH_FILE}"
  RESULT_VARIABLE PATCH_APPLY_RESULT
  OUTPUT_VARIABLE PATCH_APPLY_OUTPUT
  ERROR_VARIABLE PATCH_APPLY_ERROR
)

if(NOT PATCH_APPLY_RESULT EQUAL 0)
  message(FATAL_ERROR "Patch failed: ${PATCH_FILE}\n${PATCH_APPLY_OUTPUT}\n${PATCH_APPLY_ERROR}")
endif()

message(STATUS "Applied patch: ${PATCH_FILE}")
